'''Project constant definitions.'''

MAIN_WINDOW_WIDTH = 800
MAIN_WINDOW_HEIGHT = 600

DEFAULT_MIN_POINT_ID = 1
DEFAULT_MIN_PATH_ID = 1

DEFAULT_DELIVERY_POINT_COLOR = 'red'
DEFAULT_PARKING_POINT_COLOR = 'blue'
DEFAULT_PATH_POINT_COLOR = 'green'
DEFAULT_NON_FOLLOW_POINT_COLOR = 'yellow'

DEFAULT_POINT_RADIUS = 10
